name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js and pnpm
      - name: Setup Node.js and Enable pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.1
          cache: 'pnpm'
      - run: corepack enable # Enable pnpm via Corepack (Node.js >=16.10)

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: pnpm install

      # Step 4: Run Semantic Release
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm exec semantic-release
